package instruction

const AUTH = "AUTH"
const PRODUCER = 'P'
const CONSUMER = 'C'

const RESPONSE_AUTHENTICATED = "AUTHENTICATED"
const RESPONSE_NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
const RESPONSE_OK = "OK"
